version: "3.4"
services:
  client:
    image: node:18-alpine
    container_name: abetterworld-client
    entrypoint: /bin/sh
    ports:
      - 8000:8000
    networks:
      - abw_client
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./frontend
        target: /srv/app
    tty: true
  backend:
    image: node:18-alpine
    container_name: abetterworld-backend
    env_file:
      - .env
    entrypoint: /bin/sh
    ports:
      - 7000:7000
    networks:
      - abw_backend
      - abw_client
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./backend 
        target: /srv/app
    tty: true
networks:
  abw_client:
  abw_backend:
